version: '3.8'

services:
  db:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci   
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: home
      MYSQL_USER: user
      MYSQL_PASSWORD: 654321
    ports:
      - "3307:3306"